# Generated by Django 6.0.5 on 2026-05-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identity_type',
            field=models.CharField(blank=True, choices=[('AADHAR CARD', 'aadhar card'), ('DRIVING LICENSE', 'driving license'), ('PASSPORT', 'passport')], max_length=290, null=True),
        ),
    ]
