# Generated by Django 6.0.5 on 2026-05-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_profile_identity_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='varified',
            new_name='verified',
        ),
    ]
