# Generated by Django 6.0.5 on 2026-05-13 16:21

import userauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_rename_varified_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identity_image',
            field=models.FileField(blank=True, default='id.jpg', null=True, upload_to=userauth.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to=userauth.models.user_directory_path),
        ),
    ]
